### ISSUE TITLE
Refactor fixtures into conftest.py for test reuse and organization

### ISSUE THREAD

**Issue by atxtechbro** [atxtechbro/fashion-recommender#5]
**Description:**
Move common fixtures like \`create_user\` and \`create_clothing_item\` from individual test files to a \`conftest.py\` file to improve reusability and organization across tests.

**Steps:**
1. Create a \`conftest.py\` file in the \`snazzy-closet/backend/tests/\` directory.
2. Move the \`create_user\` fixture from \`test_user_crud.py\` to \`conftest.py\`.
3. Move the \`create_clothing_item\` fixture from \`test_clothing_item_crud.py\` to \`conftest.py\`.
4. Update the test files to use the fixtures from \`conftest.py\`.

**Expected Outcome:**
All test files that require user and clothing item fixtures should work as expected, with the fixtures centralized in \`conftest.py\`.

**Additional Information:**
This refactor will improve test organization and make it easier to manage and extend fixtures as the test suite grows.

**Comment by EhsanSl** [comment]
I can take on this one
